[package]
name = "cc2650"
version.workspace = true
authors.workspace = true
edition.workspace = true
links = "driverlib"

# [features]
# driverlib = []

[dependencies]
cortexm3 = { path = "../../arch/cortex-m3" }
kernel = { path = "../../kernel" }
cty = "0.2.2"
cc2650 = "0.1.1"
tock-cells = { path = "../../libraries/tock-cells"}

[build-dependencies]
bindgen = { version = "0.69.4", features = ["experimental"] }
cc = "1.0.90"
